export enum UserType {
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  SYSTEM_MANAGER = "SYSTEM_MANAGER",
  CAMPUS_ADMIN = "CAMPUS_ADMIN",
  CAMPUS_COORDINATOR = "CAMPUS_COORDINATOR",
  CAMPUS_TEACHER = "CAMPUS_TEACHER",
  CAMPUS_STUDENT = "CAMPUS_STUDENT",
  CAMPUS_PARENT = "CAMPUS_PARENT",
} 