import { UserType } from '@prisma/client';

export const ACADEMIC_CYCLE_PERMISSIONS = {
  // Institution Level
  MANAGE_ACADEMIC_CYCLES: 'academic_cycle.manage',
  VIEW_ALL_ACADEMIC_CYCLES: 'academic_cycle.view.all',
  
  // Campus Level
  MANAGE_CAMPUS_ACADEMIC_CYCLES: 'academic_cycle.campus.manage',
  VIEW_CAMPUS_ACADEMIC_CYCLES: 'academic_cycle.campus.view',
  
  // Class Level
  VIEW_CLASS_ACADEMIC_CYCLES: 'academic_cycle.class.view',
} as const;

// Role-based permission mappings
export const ROLE_PERMISSIONS = {
  // System Level
  SYSTEM_ADMIN: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_ALL_ACADEMIC_CYCLES,
  ] as const,
  
  SYSTEM_MANAGER: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_ALL_ACADEMIC_CYCLES,
  ] as const,

  // Institution Level
  ADMINISTRATOR: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_ALL_ACADEMIC_CYCLES,
  ] as const,

  // Campus Level
  CAMPUS_ADMIN: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_CAMPUS_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CAMPUS_ACADEMIC_CYCLES,
  ] as const,
  
  CAMPUS_COORDINATOR: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CAMPUS_ACADEMIC_CYCLES,
  ] as const,
  
  COORDINATOR: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CAMPUS_ACADEMIC_CYCLES,
  ] as const,

  // Academic Roles
  TEACHER: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
  ] as const,
  
  CAMPUS_TEACHER: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
  ] as const,

  // Student Roles
  STUDENT: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
  ] as const,
  
  CAMPUS_STUDENT: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
  ] as const,

  // Other Roles
  CAMPUS_PARENT: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
  ] as const,
} as const; 